### PR TITLE
ubuntu16.04 compile error

### PR DESCRIPTION
**Pull request by SkyOnce**
my  system information is：gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12) 
download this package and ./configure,when make ,it report compile error:
In file included from /usr/include/string.h:630:0,
                 from append.c:34:
dmalloc.h:392:7: error: expected identifier or ‘(’ before ‘__extension__’
 char *strndup(const char *string, const DMALLOC_SIZE max_len);

so,i think the ac_cv_strndup_macro variable assignment does not take effect in the configure.

### CODE REVIEW

**Comment by j256** [comment]
What version of dmalloc are you using @SkyOnce ?  What does your dmalloc.h.2 have in it?  The `export` isn't the issue but I wonder if this pull request fixes it?  https://github.com/j256/dmalloc/pull/48

**Comment by j256** [comment]
No I see the problem.  A bad merge in 5.6.2 reverted a previous fix.  Just fixed it.

**Comment by j256** [comment]
Just released 5.6.4 @SkyOnce that hopefully fixes the issue.  Thanks.
